services:
  postgres:
    image: postgres:latest
    container_name: seaorm_tutorial
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"